<?xml version="1.0" encoding="utf-8"?>
<Database Name="snakeworld" Class="snakeworldDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=snakeworld;Integrated Security=True" SettingsObjectName="SnakeWorld_Server.Properties.Settings" SettingsPropertyName="snakeworldConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SnakeInfo" Member="SnakeInfos">
    <Type Name="SnakeInfo">
      <Column Name="userId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="timeSecondsPlayed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxLength" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="kills" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="suicides" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="plays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="playDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="recordId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>